name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - run: mkdir -p output

    - name: Build
      run: go build -v -o output/grpcweb .
      
    - uses: actions/upload-artifact@v3
      with: 
        name: grpcweb
        path: output/grpcweb
    
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: set release date
      run: |
        echo "tag=$(date +'%Y%m%d%H%M%S')" >> ${GITHUB_ENV}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: grpcweb:env.tag
